//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1809301_NTAThu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public string MOTA { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<double> DONGIA { get; set; }
    }
}
